USE [CustomerJourney]
GO

/****** Object:  Table [dbo].[PhasesDBO]    Script Date: 22/12/2020 21:10:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PhasesDBO](
	[companyID] [int] NOT NULL,
	[phases] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[companyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


